### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by ekans812** [DecoyLex/Minecraft-Mod-Updater#72]
Minecraft Mod Updater has crashed.
Please make an error report about this including everything below the line.
If you make an error report about this, I will make sure it gets fixed.
The application will try to recover from this error, if you wish.

---

Application: Minecraft Mod Updater
Version: 1.3.0_1
API Version: 1.3.0
OS: Microsoft Windows NT 6.1.7600.0
Framework Version: v4.0.30319
Exception Sender: ModUpdater.Client.GUI.ExceptionHandler

System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at ModUpdater.Net.ModUpdaterNetworkStream.ReadDataType()
   at ModUpdater.Net.ModUpdaterNetworkStream.ReadNetworkByte()
   at ModUpdater.Net.Packet.ReadPacket(ModUpdaterNetworkStream Stream)

**Comment by DecoyLex** [comment]
Server forced connection closed some way or another.  What was being done when the error occurred?

**Comment by DecoyLex** [comment]
Please provide more information, then resubmit.
